### ISSUE TITLE
Bug提交和代码改善

### ISSUE THREAD

**Issue by zhongzilu** [dmcBig/MediaPickerPoject#10]
哥，库中有个地方有Bug。当选择视频后点击【预览】，然后点击播放按钮的时候会报错：
```
java.lang.IllegalArgumentException: Invalid Uri (/storage/emulated/0/DCIM/Camera/VID_20180517_062714.mp4) used for observer
```

### 建议：
1.Uri进行手动检查，并适配Android高版本系统
2.发送隐式Intent前进行检查，检查是否有可以处理的程序

Intent检查代码：
```
private boolean isIntentAvailable(Context context, Intent intent){
      List resolves = context.getPackageManager().queryIntentActivities(intent,0);
      return resolves.size() > 0;
}
```

代码文件位置：`[package_name]/view/PreviewFragment.java`

**Comment by dmcBig** [comment]
好的非常感谢你，劳烦告诉我一下具体是什么型号的手机和什么系统版本，我好方便测试和重现这个bug。

**Comment by zhongzilu** [comment]
Phone：`Nexus 5`
Android Version：`6.0.1`
Gradle Build Tools Version：`com.android.tools.build:gradle:2.3.3`
Gradle Version：`gradle-3.3-all.zip`
compileSdkVersion：`26`
buildToolsVersion：`26.0.3`
minSdkVersion：`21`
targetSdkVersion：`26`

**Comment by dmcBig** [comment]
我最近有点忙，如果您有空的话非常欢迎提交代码到pull requests.

**Comment by zhongzilu** [comment]
已提交，希望你能及时上传到gradle仓库

**Comment by dmcBig** [comment]
好

**Comment by zhongzilu** [comment]
今天能提交吗，因为我比较急，现在以有的引用使用起来有问题，会导致闪退

**Comment by dmcBig** [comment]
抱歉今天没办法提交了，我现在的电脑没有环境，只能明天了非常抱歉。

**Comment by dmcBig** [comment]
已提交到了bintray仓库

在你提交的分支有个问题，“没有可播放的程序”这个提示字段需要在string里面去配置中英文，因为英文在cordova需要用到有部分国外人用这个插件，所以我就不合并你这次的提交了，这次先在自己的分支加上你的代码。

**Comment by dmcBig** [comment]
已提交到了bintray仓库

在你提交的分支有个问题，“没有可播放的程序”这个提示字段需要在string里面去配置中英文，因为英文在cordova需要用到有部分国外人用这个插件，所以我就不合并你这次的提交了，这次先在自己的分支加上你的代码。
