### ISSUE TITLE
提个BUG

### ISSUE THREAD

**Issue by LightProspect** [dmcBig/MediaPickerPoject#14]
在拍照的时候不选择拍摄照片而是退出相机 那么这个页面就会崩溃

**Comment by LightProspect** [comment]
我用了比较笨的方法来进行判断   我打断点发现在
`select = data.getParcelableArrayListExtra(PickerConfig.EXTRA_RESULT);`
这一行发生了错误，于是我进行了传入判断
![qq 20180608095834](https://user-images.githubusercontent.com/32256992/41135107-93c3aeac-6b02-11e8-9b67-3ae904247a81.png)

**Comment by dmcBig** [comment]
谢谢，你找到了比较简洁优雅的解决方式可以pull我来合并，最近我比较忙还没空看这个问题。
