### ISSUE TITLE
和PhotoView 冲突

### ISSUE THREAD

**Issue by JamesGZM** [dmcBig/MediaPickerPoject#4]

**Comment by JamesGZM** [comment]
compile 'com.chensl.rotatephotoview:rotatephotoview:1.0.5' 这个有问题 加了这个就会报错 我有导入PhotoView最新版

**Comment by dmcBig** [comment]
意思是与你自己天津的新版本的PhotoView 冲突是吗？你如果不加是否正常呢？我这里面也引用了PhotoView的一个库但是被更改过的而且版本很老。

**Comment by JamesGZM** [comment]
@dmcBig  我这边是fork下来改了下配置  不引用我有些方法报错..
