### ISSUE TITLE
再次进入默认选择问题

### ISSUE THREAD

**Issue by Corusaki** [dmcBig/MediaPickerPoject#6]
第一次进去选择了视频，确定以后再进去 上次选择的默认选择了。怎么才能不让默认选择

**Comment by dmcBig** [comment]
Intent intent =new Intent(MainActivity.this, PickerActivity.class);
    intent.putExtra(PickerConfig.SELECT_MODE,PickerConfig.PICKER_IMAGE_VIDEO);//default image and video (Optional)
    long maxSize=188743680L;//long long long
    intent.putExtra(PickerConfig.MAX_SELECT_SIZE,maxSize); //default 180MB (Optional)
    intent.putExtra(PickerConfig.MAX_SELECT_COUNT,15);  //default 40 (Optional)
   // intent.putExtra(PickerConfig.DEFAULT_SELECTED_LIST,select); //注释掉这行，这就是默认选中参数
    MainActivity.this.startActivityForResult(intent,200);

**Comment by Corusaki** [comment]
是我傻逼了，没仔细看。。谢谢
